---
title: "Quarto Assignment"
subtitle: "Unicef indicators and its analysis"
author: Chethan Kashyap Ravikumar
date: "2024-04-25"
format: html
theme: Sandstone
backgroundcolor: lightgrey
toc: true
execute: 
  echo: false
  warning: false
---

```{r}
#| label: setup
#| include: false

# libraries
library(tidyverse)
library(plotly)

# data
unicef_indicator_2 <- read_csv("unicef_indicator_2.csv")
unicef_indicator_1 <- read_csv("unicef_indicator_1.csv")

#transformation
data_join <- full_join(unicef_indicator_1, unicef_indicator_2, by = join_by("country", "alpha_2_code", "indicator", "time_period",))
```

```{r}
#| fig-cap: "This world map shows how many countries unicef has taken into account to validte indicators for the year 2019 and how each coutnry performed"
map_world <- map_data("world")

map_data_join <- full_join(data_join, map_world, by = c("country" = "region"))

ggplot(map_data_join) +
  aes(x = long, y = lat, group = group, fill = indicator) +
  geom_polygon() + labs(title = "world map chart of <indicator>")


```

```{r}
barchart <- ggplot() +
aes(x = "country", y = "obs_value", fill = "indicators") +
geom_bar(stat = "identity", fill = "steelblue") +
labs(title = "bar chart of indicators")
print(barchart)
```

```{r}
#| fig-cap: this is a raw visual representation of the Observation value of the indicator represented in the report 
ggplot() + aes(x = "country", y = "obs_value", fill = "indicators") +  
  geom_point() +
  geom_smooth(method = "lm", color = "blue") +
  labs(title = "Scatterplot with Linear Regression")
print(scatter.smooth)
```

```{r}
ggplot()+ aes(x = "country", y = "obs_value", fill = "indicators") +  
  geom_line() +
  labs(title = "Time Series Chart of Indicator")

```
